{
 "title": "moq-rs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stream",
    "query": {
     "query": "label_values(publisher_bytes_sent_total,stream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput: $stream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "stream",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(publisher_bytes_sent_total{stream=~\"$stream\"}[1m]))",
     "legendFormat": "{{stream}} (Pub)"
    },
    {
     "expr": "sum(rate(subscriber_bytes_received_total{stream=~\"$stream\"}[1m]))",
     "legendFormat": "{{stream}} (Sub)"
    }
   ]
  },
  {
   "title": "E2E Network Usages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (stream) (rate(publisher_bytes_sent_total{stream!=\"\"}[1m]))",
     "legendFormat": "{{stream}} (Pub)"
    },
    {
     "expr": "sum by (stream) (rate(subscriber_bytes_received_total{stream!=\"\"}[1m]))",
     "legendFormat": "{{stream}} (Sub)"
    }
   ]
  },
  {
   "title": "Relay Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_bytes{job=\"moq-relay\"}",
     "legendFormat": "Relay RSS"
    }
   ]
  },
  {
   "title": "Track Sync",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stream) (publisher_active_tracks) - sum by (stream) (subscriber_active_tracks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E Object Loss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (stream) (rate(publisher_objects_sent_total[1m])) - \n(sum by (stream) (rate(subscriber_objects_received_total[1m])) / \n count by (stream) (rate(subscriber_objects_received_total[1m]) > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pub/Sub CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (stream) (process_cpu_usage_percent{role=\"publisher\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (stream) (process_cpu_usage_percent{role=\"subscriber\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_bytes{job=\"moq-relay\"} - system_memory_available_bytes{job=\"moq-relay\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_available_bytes{job=\"moq-relay\"}",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Connection Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(moq_relay_bytes_received_from_publisher_total{job=\"moq-relay\"}[1m])",
     "legendFormat": "{{relay_id}} Ingress Traffic"
    },
    {
     "expr": "rate(moq_relay_bytes_sent_to_subscriber_total{job=\"moq-relay\"}[1m]) * -1",
     "legendFormat": "{{relay_id}} Egress Traffic"
    }
   ]
  },
  {
   "title": "Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "system_cpu_usage_percent{job=\"moq-relay\"}",
     "legendFormat": "System Total"
    },
    {
     "expr": "process_cpu_usage_percent{job=\"moq-relay\"}",
     "legendFormat": "Moq Relay Process"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "moq_relay_quic_rtt_milliseconds",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Packet Loss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(moq_relay_quic_lost_packets[1m])",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Namespace Popularity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(subscriber_active_tracks{role=\"subscriber\"}) by (stream)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}